
version: '3'

services:
  sonarqube:
    image:  library/sonarqube:8.6-community
    ports:
      - "9000:9000"

  mongodb:
    image:  mongo
    ports:
      - "8081:27017"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
