spring:
  data:
    mongodb:
      host: localhost
      port: 8081

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false